<?php

if (!defined('ABSPATH'))
    die('Restricted Access');

class JSVehicleManagerUser {

    private $currentuser = null;
    public $socialmedia = null;

    function __construct() {
        $db = new jsvehiclemanagerdb();
        if (is_user_logged_in()) { // wp user logged in
            $wpuserid = get_current_user_id();
            if (!is_numeric($wpuserid))
                return false;
            $query = "SELECT * FROM `#__js_vehiclemanager_users` WHERE uid = " . $wpuserid;
            $db->setQuery($query);
            $currentuser = $db->loadObject();
            $jsvehiclemanager_registerform = JSVEHICLEMANAGERrequest::getVar('jsvehiclemanager_autoz_register_nonce','post','');
            $registerform = JSVEHICLEMANAGERrequest::getVar('jsvehiclemanager_registerform','post',0);
            if($currentuser == '' AND ($jsvehiclemanager_registerform == '' && $registerform == 0) ){// inserting a record in our table
                $userdata = get_userdata($wpuserid);
                $profile['id'] = '';
                // User display name
                $user_first = get_user_meta($wpuserid , 'first_name' , true);
                $user_last = get_user_meta($wpuserid , 'last_name' , true);
                if ( $user_first && $user_last ) {
                    $display_name = sprintf( _x( '%1$s %2$s', 'Display name based on first name and last name' ), $user_first, $user_last );
                } elseif ( $user_first ) {
                    $display_name = $user_first;
                } elseif ( $user_last ) {
                    $display_name = $user_last;
                } else {
                    $display_name = $userdata->display_name;
                }

                $profile['name'] = $display_name;
                if($userdata->display_name == ''){
                    $profile['name'] = $userdata->user_nicename;
                }
                $profile['email'] = $userdata->user_email;
                $profile['uid'] = $wpuserid;
                $profile['created'] = date_i18n('Y-m-d H:i:s');
                $profile['status'] = 1;
                $profile['autogenerated'] = 1;
                $result = JSVEHICLEMANAGERincluder::getJSModel('user')->storeProfile($profile,2);
                if(is_numeric($result)){
                    $query = "SELECT * FROM `#__js_vehiclemanager_users` WHERE id = " . $result;
                    $db->setQuery($query);
                    $currentuser = $db->loadObject();
                }
            }
            $this->currentuser = $currentuser;
        }else { // wp user is not logged in
            do_action('jsvm_userid_by_sociallogin',$this);
        }
    }

    function isguest() {
        if (isset($_COOKIE['jsvehiclemanager-socialid']) && !empty($_COOKIE['jsvehiclemanager-socialid'])) {
            if(in_array('sociallogin', jsvehiclemanager::$_active_addons)){
                return false;
            }else{
                return true;
            }
        } elseif ($this->currentuser == null && !is_user_logged_in()) { // current user is guest
            return true;
        } else {
            return false;
        }
    }

    function isdisabled() {
        if ($this->currentuser != null && $this->currentuser->status == 0) { // current user is disabled
            return true;
        } else {
            return false;
        }
    }

    function uid() {
        if ($this->currentuser != null) {
            return $this->currentuser->id;
        }
    }

    function emailaddress() {
        if ($this->currentuser == null) { // current user is guest
            return false;
        } else {
            return $this->currentuser->emailaddress;
        }
    }

    function fullname() {
        if ($this->currentuser == null) { // current user is guest
            return false;
        } else {
            $name = $this->currentuser->name;
            return $name;
        }
    }

    function getAvailableCredits() {
        $isadmin = JSVEHICLEMANAGERrequest::getVar('isadmin');
        $userid = JSVEHICLEMANAGERrequest::getVar('userid');
        if($isadmin && is_numeric($userid)){
            $uid = $userid;
        }else{
            $uid = $this->uid();
        }
        $credits = apply_filters('jsvm_credits_get_user_avaiable_credits',0,$uid);
        return $credits;
    }

    function getAvailableCreditsForUser($uid) {
        if (!is_numeric($uid))
            return false;
        $credits = apply_filters('jsvm_credits_get_user_avaiable_credits',0,$uid);
        return $credits;
    }

    function isJSVehicleManagerUser() {
        $db = new jsvehiclemanagerdb();
        if (is_user_logged_in()) { // wp user logged in
            $wpuserid = get_current_user_id();
            if (!is_numeric($wpuserid))
                return false;
            $query = "SELECT COUNT(id) FROM `#__js_vehiclemanager_users` WHERE uid = " . $wpuserid;
            $db->setQuery($query);
            $result = $db->loadResult();
            if ($result > 0) {
                return true;
            } else {
                return false;
            }
        } else {
            if (isset($_COOKIE['jsvehiclemanager-socialid']) && !empty($_COOKIE['jsvehiclemanager-socialid'])) { // social user is logged in
                $query = "SELECT COUNT(id) FROM `#__js_vehiclemanager_users` WHERE socialid = '" . $_COOKIE['jsvehiclemanager-socialid'] . "'";
                $db->setQuery($query);
                $result = $db->loadResult();
                if ($result > 0) {
                    return true;
                } else {
                    return false;
                }
            }
        }
    }

    function isSocialLogin() {
        if (isset($_COOKIE['jsvehiclemanager-socialid']) && !empty($_COOKIE['jsvehiclemanager-socialid'])) {
            return true;
        } else {
            return false;
        }
    }

    function getjsvehiclemanageruidbyuserid($userid){
        if(!is_numeric($userid)) return false;
        $db = new jsvehiclemanagerdb();
        $query = "SELECT id FROM `#__js_vehiclemanager_users` WHERE uid = ".$userid;
        $db->setQuery($query);
        $uid = $db->loadResult();
        return $uid;
    }

    function isSeller(){
        $uid = $this->uid();
        if(!is_numeric($uid) || $uid == ''){
            return false;
        }
        $db = new jsvehiclemanagerdb();
        $query = "SELECT COUNT(veh.id) FROM `#__js_vehiclemanager_vehicles` AS veh WHERE veh.uid = ".$uid;
        $db->setQuery($query);
        $total = $db->loadResult();
        if ($total > 0) {
            return true;
        }
        return false;
    }

    function isSellerCheck($uid){
        if(!is_numeric($uid) || $uid == ''){
            return false;
        }
        $db = new jsvehiclemanagerdb();
        $query = "SELECT COUNT(veh.id) FROM `#__js_vehiclemanager_vehicles` AS veh WHERE veh.uid = ".$uid;
        $db->setQuery($query);
        $total = $db->loadResult();
        if ($total > 0) {
            return true;
        }
        return false;
    }
}
?>
