<?php

if (!defined('ABSPATH'))
    die('Restricted Access');

class jsvehiclemanagerxing {

    private $client;

    function __construct() {
        include_once(jsvehiclemanager::$_path . 'includes/lib/http.php');
        include_once(jsvehiclemanager::$_path . 'includes/lib/oauth_client.php');
        $this->client = new oauth_client_class;
        $this->client->debug = 0;
        $this->client->debug_http = 1;
        $this->client->server = 'XING';
        $this->client->redirect_uri = jsvehiclemanager::makeUrl(array('jsvehiclemanagerpageid'=>JSVEHICLEMANAGERRequest::getVar('jsvehiclemanagerpageid'), 'jsvmme'=>'user', 'action'=>'jsvmtask', 'task'=>'sociallogin', 'media'=>'xing'));
        $application_line = __LINE__;
        $config_array = JSVEHICLEMANAGERincluder::getJSModel('configuration')->getConfigByFor('xing');
        $this->client->client_id = $config_array['apikeyxing'];
        $this->client->client_secret = $config_array['clientsecretxing'];
        if (strlen($this->client->client_id) == 0 || strlen($this->client->client_secret) == 0)
            wp_die('Please go to XING My Apps page https://dev.xing.com/applications , ' . 'create an application, and in the line ' . $application_line . ' set the client_id to Consumer key and client_secret with Consumer secret.');
    }

    private function callAPI() {
        // API permissions
        $user = null;
        if (($success = $this->client->Initialize())) {
            if (($success = $this->client->Process())) {
                if (strlen($this->client->access_token)) {
                    $success = $this->client->CallAPI(
                            'https://api.xing.com/v1/users/me', 'GET', array(), array('FailOnAccessError' => true), $user);
                }
            }
            $success = $this->client->Finalize($success);
        }
        return array($success, $user);
    }

    function login() {
        $result = $this->callAPI();
        $success = $result[0];
        $user = $result[1];
        if ($this->client->exit) {
            exit;
        }
        if ($success) {
            $user = $user->users[0];
            $socialid = $user->id;
            $result = JSVEHICLEMANAGERincluder::getJSModel('user')->checkUserBySocialID($socialid);
            $_SESSION['jsvehiclemanager-socialid'] = $socialid;
            $_SESSION['jsvehiclemanager-socialmedia'] = 'xing';
            $_SESSION['jsvehiclemanager-socialfirstname'] = $user->first_name;
            $_SESSION['jsvehiclemanager-sociallastname'] = $user->last_name;
            $_SESSION['jsvehiclemanager-socialemail'] = $user->active_email;
            if(!$result){
                $row = JSVEHICLEMANAGERincluder::getJSTable('users');
                $data['id'] = '';
                $data['name'] = $user->first_name.' '.$user->last_name;
                $data['email'] = $user->active_email;
                $data['issocial'] = 1;
                $data['status'] = 1;
                $data['socialid'] = $socialid;
                $data['autogenerated'] = 1;
                $row->bind($data);
                $row->store();
            }
            if ($result > 0) {
                return 2; // user login and our user
            } else {
                return 3; // user login and not our user
            }
        } else {
            echo HtmlSpecialChars($this->client->error);
            return 4; // api not send the data
        }
    }

    function logout() {
        // Logout xing user from our system
        if (isset($_SESSION['jsvehiclemanager-socialmedia']) && $_SESSION['jsvehiclemanager-socialmedia'] == 'xing') {
            unset($_SESSION['jsvehiclemanager-socialid']);
            unset($_SESSION['jsvehiclemanager-socialmedia']);
            unset($_SESSION['jsvehiclemanager-socialfirstname']);
            unset($_SESSION['jsvehiclemanager-sociallastname']);
            unset($_SESSION['jsvehiclemanager-socialemail']);
            unset($_SESSION['OAUTH_STATE']);
            unset($_SESSION['OAUTH_ACCESS_TOKEN']);
            $this->client->ResetAccessToken();
            return 1;
        } else {
            return 0;
        }
    }

}

?>